name: Npm Publish
on: 
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
      
      - name: Install modules
        run: npm install
        
      - name: Stash 
        run: git stash
        
      - name: GitHub Tag Name example
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      # Bump package version
      # Use tag latest
      - name: Bump release version
        run: npm version ${{  github.ref_name }}
        
      - name: Pop
        run: git pop

      - name: Publish to NPM
        run: npm publish — access public
        env:
         NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
