name: Npm Publish
on: 
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
      
      - name: Install modules
        run: npm install
        
      - name: GitHub Tag Name example
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      # Bump package version
      # Use tag latest
      - name: Bump release version
        run: npm --no-git-tag-version version  from-git
        
      - name: Commit Files
        run: |
          git config --global user.name "Chinmay-Kalmane"
          git config --global user.email "kalmane3101@gmail.com"
          git checkout -b release-${{  github.ref_name }}
          git branch
          git add "package.json"
          git add "package-lock.json"
          git status
          git commit -m "Updated `package.json` with new release version"
          git status
          git push origin main
#          git checkout main
#           git merge release-${{  github.ref_name }}
#          git log --oneline
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npm publish
        env:
         NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
